### ISSUE TITLE
LegendControl of the `charites serve` command has broken

### ISSUE THREAD

**Issue by yuiseki** [unvt/charites#117]
**Describe the bug**

- MaplibreLegendControl and MapboxLegendControl of the `charites serve` command is currently broken

**To Reproduce**

1. Pull newest `main` branch of charites
2. `npm ci`
3. `npm run build`
4. `charites serve test/data/style.yml`
5. Open http://localhost:8080/
6. Open Chrome Dev Tool
7. See console log

**Expected behavior**

- MapboxLegendControl has shown

**Screenshots**

### Before

[![Image from Gyazo](https://i.gyazo.com/c9bb408b608cd3ae835725a1b00bbd5b.png)](https://gyazo.com/c9bb408b608cd3ae835725a1b00bbd5b)

### After

[![Image from Gyazo](https://i.gyazo.com/8107c06bb0726b357aac7dc3fbced939.png)](https://gyazo.com/8107c06bb0726b357aac7dc3fbced939)

**Charites Version:**

- Charites version: 0.2.0

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: Google Chrome 107.0.5304.107

**Additional context**
I will immediately submit pull request that fix this issue

**Comment by ubukawa** [comment]
Thank you for this improvement! It is really helpful!
