### ISSUE TITLE
">" causes some issue when running "build" 

### ISSUE THREAD

**Issue by ubukawa** [unvt/charites#127]
**Describe the bug**
If the "id" of any layer in "layers" is long,  ">" 「折り返し形式のブロックスカラー」 is used in the layer list during the import, and it causes problem when we build JSON from YAML. 

**To Reproduce**

1. Prepare a style json with a long layer name.
2. Import that JSON file into YAML.
3. Confirm that ">"  is used together with "!!inc/file." 
4. Build a newe JSON form imported YAML file.
5. Then, you will see an error that says "Cannot use 'in' operator to search for 'ref' in !!inc/fil ...."

**Expected behavior**
Build can be successfully done.

**Screenshots**
![image](https://user-images.githubusercontent.com/59204379/204708169-e2146876-6902-43be-97ce-9a3cb3112252.png)

![image](https://user-images.githubusercontent.com/59204379/204709234-b99f489e-4f46-415f-9088-4a034ba31347.png)

**Charites Version:**

- Charites version: keichan34/charites:upport-slash-in-layer-id https://github.com/keichan34/charites/tree/support-slash-in-layer-id

**Desktop (please complete the following information):**

- OS: [e.g. Windows] Windows/Docker (unvt/nanban)

**Additional context**

**Comment by keichan34** [comment]
OK, I think I know why this isn't being parsed correctly.

`!!inc/file` is a [YAML tag? type? statement](https://github.com/nodeca/js-yaml#supported-yaml-types), and is probably not parsed as such when using a multiline statement such as `>-` (I found [this](https://stackoverflow.com/a/21699210) when looking up multiline statements... :eyes: )

As a solution, I think maybe setting `lineWidth: -1` for unlimited width when running `YAML.dump` would work? I don't necessarily like this solution...

Maybe as an alternative we can try removing the replace here:
https://github.com/unvt/charites/blob/3a6b5ec81b4915d0479342ced405a83f0810dade/src/lib/yaml-writer.ts#L65-L70
and replacing it with a non-string type that directly translates to `!!inc/file` when running YAML.dump?

https://github.com/unvt/charites/blob/3a6b5ec81b4915d0479342ced405a83f0810dade/src/lib/yaml-writer.ts#L55-L58

Looking at yaml-include, it doesn't look like we can use that, so we could possibly make a temporary schema just for this:

```
class IncFileTag {
  constructor(fileName) {
    this.value = path.posix.join('layers', fileName)
  }
}

const incFileYamlType = new yaml.Type('!!inc/file', { kind: 'scalar', resolve: data => data, construct, data => new IncFileTag(data), instanceOf: IncFileTag, represent: tag => tag.value })
const schema = yaml.Schema.create([incFileYamlType])

...
layers.push(new IncFileTag(fileName))
...

yaml.dump(style, { schema: schema })
```

(I haven't tested it yet... I'll try to get around to trying to fix this in the near future if nobody else wants to.. :slightly_smiling_face:  )

**Comment by ubukawa** [comment]
Thank you very much for your consideration. Although I cannot immediately understand your script, I keep watching this!

This is the issue, I have written here.
https://unvt.github.io/charites/usage/example2.html#step-2-checking-an-overall-yaml-style-yml-in-this-case

">-" is good if it appears in "attribution" and others, but not in "layers."
