### ISSUE TITLE
レイヤーの一覧表示と、プレビューでのハイライト

### ISSUE THREAD

**Issue by ShinichiNishikawa** [unvt/charites#14]
プレビュー画面において作業中に、

* レイヤーは何があるのか
* どのレイヤーを触ると何が変わるのか

を知りたい。
提案としては、プレビュー画面にレイヤーの一覧が掲載されており、レイヤー名をクリックすると、対象の地物等が少し大きくなって光る（薄くなる？）ようなことができると、インスピレーションが浮かびやすくなる。

**Comment by miya0001** [comment]
@ShinichiNishikawa  We need to re-open this issue in English. 😊
