### ISSUE TITLE
Typo (??) in help for initialize

### ISSUE THREAD

**Issue by ubukawa** [unvt/charites#142]
**Describe the bug**
I am not 100% for sure, but there could be typo in the explanation of "init" command.

**To Reproduce**

1. Start charites
2. charites init --help
3. You will see the explanation. It says "initialize a style JSON", but we are creating YAML.

**Expected behavior**
 It should say "initalize a style YAML" or "initialize a style"

**Screenshots**
![image](https://user-images.githubusercontent.com/59204379/208183041-0301a014-fbef-4f5f-a09b-c1282369dd53.png)

**Charites Version:**

- Charites version: 0.3.0

**Desktop (please complete the following information):**

- OS: docker (unvt/nanban)

**Additional context**

**Comment by keichan34** [comment]
Yeah, this is a typo. Thanks!

**Comment by iamr-kumar** [comment]
Can I submit a PR for this?

**Comment by ubukawa** [comment]
Thank you!!
