### ISSUE TITLE
[urgent] requires upgrading Transifex CLI tool

### ISSUE THREAD

**Issue by JinIgarashi** [unvt/charites#153]
I have received a notification from transifex that the old Transifex API used in charites will no longer work after 12 February 2023. It requires to be upgraded to new API/CLI by that time.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/2639701/215473570-b3df7292-99a5-4581-be4e-5245e7c6d901.png">

I will not work with this issue since I am no longer a member of this charites project.

@hfu @ubukawa Please assign a right person and upgrade the transifex CLI tool. If you need to transfer my owner permission of transifex to someone else, I am willing to do so. Please let me know to whom I will transfer permission.

references
- [announcement](https://community.transifex.com/t/important-reminder-api-tx-cli-deprecation/3202?utm_campaign=Product%20Updates&utm_medium=email&_hsmi=243729257&_hsenc=p2ANqtz-_8lbGM1PN80IN5IQQHKuAEuLyNfHrmn4rsS9cxw2-1hDFtrf6OvGlASkD8l5gHzCVzFOKswBwmqm2J70IaNazSJfPeyg&utm_content=243729257&utm_source=hs_email)
- [CLI](https://developers.transifex.com/docs/using-the-client?utm_campaign=Product%20Updates&utm_medium=email&_hsmi=243729257&_hsenc=p2ANqtz-9NJgtglF9X6wAEjLcYwNriMx2OYveuV21TZHwc70yEs9hhNWpxcsosdaxk656CRYIz-LBj3hR6eMZoQ5PFrq8M1dOL-w&utm_content=243729257&utm_source=hs_email)

**Comment by ubukawa** [comment]
Hello @JinIgarashi . Thank you very much for your contribution and letting us know.
I now have my account in Transifex, so please let me join in the project.

I am quite a newbie of this tool, but I will explore it this week. 
Thank you.

**Comment by JinIgarashi** [comment]
@ubukawa and @hfu, I added both of you as owner of unvt organization in transifex.

**Comment by ubukawa** [comment]
Thank you @JinIgarashi . Now I can access the project.
Although I checked website, I could not find how I can migrate API, so I have just contacted the transifex support. I will try.

**Comment by ubukawa** [comment]
Dear @JinIgarashi ,

I contacted transfex and here is the list of endpoints that needs update.

![image](https://user-images.githubusercontent.com/59204379/217075477-a6b1a7dc-e1a7-4a58-b217-364f6741e25a.png)

I do not have any idea how I can replace them.
Do you know how we can replace them?
I am not sure which file I should edit. 

Thank you very much for your kind advice.

**Comment by JinIgarashi** [comment]
@ubukawa it uses `transifex-client` v0.14.4

https://github.com/unvt/charites/blob/bead559fdb72d3097c236ef97fc296ccc73ccc57/docs/Pipfile#L10

Looks like this library is not compatible with new API. Check pypi page.

https://pypi.org/project/transifex-client/

probably you need to use new CLI tool. There is a link (https://github.com/transifex/cli) in pypi.

You can ask other people in Geolonia to fix this issue if you are not sure how to figure out. I heard UNVT has a contract with them to maintain this repository.

**Comment by JinIgarashi** [comment]
@ubukawa, @hfu  could you fix transifex CI as soon as possible. I am receiving alert notifications by email everyday and it’s very annoying.

if you can’t figure out soon, could you delete CI, please? Or you can completely delete documentation from this repository if UN open GIS will never want to maintain them.

**Comment by ubukawa** [comment]
Dear @JinIgarashi ,
Thank you for your message.
I am sorry that I was stuck on updating CI. I will try again.

I am trying to upgrade the "transifex-client" package in docs/pipefile.
As I only see config file in docs/.tx, I could not find where you installed transifex/cli in unvt/charites. 
Can you advise where you installed CI, if possible?

I wonder why alert notification email does not come to me as I am also a manager of charites-docs in transifex... 

Thank you. 
My sincere apology for a number of alert notifications.

**Comment by JinIgarashi** [comment]
@ubukawa it is because CI still uses api token generated by my account. Could you kindly generate your own token and replace `TX_TOKEN` secret in setting page?

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/2639701/223182710-46650b75-8a74-4039-ba32-1bf5a0621e5c.png">

**Comment by JinIgarashi** [comment]
@ubukawa transifex-client was installed in pipenv. You can delete transifex-client from pipenv, and install new client library in  github action. I don't think there is python package which can handle new API

**Comment by ubukawa** [comment]
Thank you @JinIgarashi .
I do not see any menu to replace the token in the setting page of "charites-docs" project in transifex.
Can you kindly check it?

If there is no python package that can handle with the new API of transifex, I think we can disable it for the time being.
(Until we have the tool, we can use only sphinx to update/manage our English documents.)
What do you think?

If so, we may need to edit build.yml and build-docs.yml, and we would also ask other contributors to see if they are okay with it.
Thank you for your kind advice!

**Comment by JinIgarashi** [comment]
@ubukawa for new API client, please refer my previous comment. You should install transifex client in CI itself.

https://github.com/unvt/charites/issues/153#issuecomment-1426833893

please look this to generate token.

https://help.transifex.com/en/articles/6248858-generating-an-api-token

**Comment by ubukawa** [comment]
Thank you! 
I did generate my token, but the issue was that I was not sure where I can replace the token. Now, I found it and successfully replaced. 

I am not so good at python as I do not often use it, but let me try with pipfile.

I realized that we have an alert everyday because we run build-docs.yml everyday. At least, by reducing the frequency of the update, we can reduce the alert immediately.
Once we update CLI, we can go back to the original update frequency.

**Comment by ubukawa** [comment]
Now, I somehow understand the issue.
- We have used Sphinx (for documentation) and Transifex (for multilingual) for the documentation.
- Transifex updated its API, but our tool (transifex-client) no longer supports the latest Transifex API. Every time we run the build-doc.yml, there is an alert.

Here, I think we technically have two options:
- Develop alternative function/workflow with other tool like transifex/cli
- Or, we can just suspend the link to the multilingual part. (And I replaced the Transifex Token with mine)

Within my ability, the first option would be difficult. 
So, I prefer the second option, but I may need to share the situation with colleagues.

**Comment by ubukawa** [comment]
Dear @JinIgarashi ,

I have replaced the TX_Token, but I have not receive any alert so far.
Can you check if you still receive them?

In addition, I would like to propose a minor change in build-docs.yml.
Please approve the following PR? Thank you!

https://github.com/unvt/charites/pull/155

**Comment by JinIgarashi** [comment]
@ubukawa 
I was removed from this repo by geolonia, I am no longer a member of this repo, also I don't have any permission to review PR. If you need a review, don't ask me again unless UNVT bring me back to the member.

I created PR #157. there is error in CI `TX_TOKEN not set, skip tx pull`. looks like no tx_token is registered in github repo. Could you register TX_TOKEN in secrets?  migration was quite straightforward.

**Comment by ubukawa** [comment]
Dear @JinIgarashi ,
Thank you for letting me know. Oh, I see. TX_TOKEN is notworking.

I will register it again.
(number + "/" part may not be necessary in transifex token...)
![image](https://user-images.githubusercontent.com/59204379/224482687-18713e2f-a154-4176-829c-3e72e9282c45.png)

**Comment by JinIgarashi** [comment]
@ubukawa can you merge PR. Let’s see how CI works

**Comment by ubukawa** [comment]
Dear @JinIgarashi ,
Thank you! I have merged PR. Thank you!

**Comment by JinIgarashi** [comment]
@ubukawa thanks for merging. I saw CI failed.
https://github.com/unvt/charites/actions/runs/4408165680/jobs/7722854078

**Comment by ubukawa** [comment]
Yes, indeed. I have just seen it. Do you have any advice if you have any?

![image](https://user-images.githubusercontent.com/59204379/224792989-7738fa5f-a095-4777-a7d9-ee5a3f97a686.png)

**Comment by JinIgarashi** [comment]
@ubukawa I created new PR. changed to use their github action intead of installing manually. hope it will work

https://github.com/unvt/charites/pull/158

**Comment by JinIgarashi** [comment]
@ubukawa i saw GitHub actions failed

**Comment by JinIgarashi** [comment]
https://github.com/opengisch/QField-docs/blob/master/.github/workflows/gh-pages.yml

Maybe we can follow their CI

**Comment by JinIgarashi** [comment]
@ubukawa I saw CI is failing. Looks like your set token having issues. Could you fix CI?

**Comment by ubukawa** [comment]
Thank you @JinIgarashi ! I have pasted my token again.

**Comment by JinIgarashi** [comment]
@ubukawa CI looks working now. Please close the issue if you confirm

**Comment by ubukawa** [comment]
Thank you @JinIgarashi !

I moved from New York to Tsukuba in the end of March and I am sorry for the delay in my response.
I have not yet established the working einvironment here, but I will close this issue once I confirm. 

Thank you very much for your contirubution!
