### ISSUE TITLE
Release new version with pmtiles support

### ISSUE THREAD

**Issue by JinIgarashi** [unvt/charites#162]
could you please release new version with pmtiles support?

**Comment by smellman** [comment]
@miya0001 How to release new version?
I can add tag but I don't know how to publish.

**Comment by JinIgarashi** [comment]
you can increment package version by `npm version patch` or `npm version minor` or `npm version major`, then push it to remote branch. CI will release new version

**Comment by smellman** [comment]
I released v0.5.1 release.
