### ISSUE TITLE
merge multiple sprite files into a single sprite

### ISSUE THREAD

**Issue by JinIgarashi** [unvt/charites#30]
This might be related to https://github.com/unvt/charites/issues/29.

Combination of multiple style.json can be done manually, however currently there is no easy way to merge multiple source of sprite into a single sprite unless we generate sprite files from original SVG icons.

It would be great if charites have a feature to merge multiple sprite files although I am not very sure whether it is possible technically...

**Comment by keichan34** [comment]
Since maplibre introduced [multiple stylesheets per style.json](https://maplibre.org/maplibre-style-spec/sprite/#multiple-sprite-sources), I think this is no longer needed. I built a simple service to merge stylesheets, but we've deprecated it in favor of that feature. What do you think?
