### ISSUE TITLE
Can not use `--provider` and `--mapbox-access-token`

### ISSUE THREAD

**Issue by naogify** [unvt/charites#58]
When I use mapbox style with `charites serve style.yml --provider mapbox --mapbox-access-token my-access-token`

It will display error in console in debug tool of Google Chrome.

```
evented.js:140 Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
    at ajax.js:183
```

**Comment by JinIgarashi** [comment]
This is my humble suggestion. Currently, both `--provider` and `--mapbox-access-token` options are only used for `charites serve` command. It is not necessary to have both options as global parameters. We can move both of them into local parameters of `serve` command.
