### ISSUE TITLE
Create contributors list within the repository

### ISSUE THREAD

**Issue by JinIgarashi** [unvt/charites#67]
This idea was come from @hfu at https://github.com/unvt/charites/pull/65#pullrequestreview-817091918

**Comment by JinIgarashi** [comment]
@hfu @ubukawa  I found this Github App to add contributors easily.
https://allcontributors.org/docs/en/bot/installation

I tried in my own documentation repository. You can see this repo's README.md how it can work.
https://github.com/watergis/docs/issues/3

If we add a comment on existing issue or PR, the bot will create a PR automatically to add the end of README.md.
```
@all-contributors please add @JinIgarashi for code
```

this one can use organization name instead of username, so you can add some organization like geolonia if you want to mention.
It can also change emoji for specific activities from users. see https://allcontributors.org/docs/en/emoji-key

It requires permission as an owner of organization in order to use this App. If you like this feature, could you setup and try this?

**Comment by ubukawa** [comment]
Thank you! I think this is a good idea. 
Dear @hfu, do you have any comment? If you are okay, I will try to setup this.

**Comment by hfu** [comment]
Thanks! Looks good to me. @ubukawa san, could you set this up?

**Comment by ubukawa** [comment]
Dear @JinIgarashi  and @hfu ,
I tried and set up this at my folk repository.
https://github.com/ubukawa/charites/tree/add_contributor

I edited only README.md and .all-contributorsrc

Which repository shall I send a PR?

all-contributor is now installed in unvt/charites.
Please also feel free to advise me any of config setting.

**Comment by JinIgarashi** [comment]
@ubukawa That is great you have experimented in forked repository. I think you can directly add contributors by all-contributors app instead of forking and creating pull requests.

**Comment by JinIgarashi** [comment]
@all-contributors please add @geolonia for code

**Comment by JinIgarashi** [comment]
@ubukawa @hfu I added @geolonia through above comments. The app created PR #70. Could you merge it if it is okay?

https://github.com/unvt/charites/tree/all-contributors/add-geolonia

Also, you can add other contributors through comments.

**Comment by ubukawa** [comment]
Oh, I thought I had to prepare config file and some space in README, but now I am happy to see that it works well.
I cannot merge it as I do not have reviewing right, but it looks good to me. Thank you!

**Comment by JinIgarashi** [comment]
@ubukawa sorry, I forgot to add you as reviewer of that PR #70. Could you try it again?

**Comment by ubukawa** [comment]
Hello @JinIgarashi ,
I am sorry to be late, but I have confirmed it and merged.

I am not sure if we need to keep the branch all-contributor/add-geolonia. 
Please delete it if it is no longer necessary. (Each time we add, do need to delete these branches manually?)

**Comment by JinIgarashi** [comment]
@ubukawa Thank you for merge it. Yes, I think it is better to delete branches after merging. It might be better to do settings for deleting merged branch automatically.

I don't have permission to change settings. Could you try to change settings by the following link?

https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by ubukawa** [comment]
Thank you @JinIgarashi  for your prompt comment.
I did not know there is such a good function. Thank you.

On the other hand, I guess that configuration will be applied to the whole repository in our future work.
Do you think all of our colleagues are okay with that configuration??? (I have no idea about it.)
(or, for the time being, I can delete the branch manually.)

Thank you!

**Comment by JinIgarashi** [comment]
I think it is no problem to delete merged branch. In fact, you can restore deleted branch anytime from PR.

Could you check branch protection settings for `main` branch (see the below link)? If branch protection was configured to specific branch like `main`, that protected branch will not be deleted automatically.

https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by ubukawa** [comment]
Thank you @JinIgarashi .
Then, I have enabled that option. Thank you for your patience and kind explanation.

Please feel free to close this issue.

**Comment by JinIgarashi** [comment]
Let me close this issue now.
@hfu @ubukawa @miya0001 Please add contributors anytime through all contributors app if necessary.
