### ISSUE TITLE
Add `charites serve` supports multiple port

### ISSUE THREAD

**Issue by naogify** [unvt/charites#73]
**Is your feature request related to a problem? Please describe.**

Currently, only http://localhost:8080 is supported by `charites serve`.

I would like to use another port if the port is already in use, since I want to use multiple `charites serve` or `tileservergl `and `charites serve` together.

**Describe the solution you'd like**
If the port is already in use, I want the port number to be incremented.

**Comment by JinIgarashi** [comment]
@naogify It is good idea, but this can be low priority. I don't think most of users need to create their own tile server from scratches.
Maybe, we can implement this for v1.0.0

**Comment by naogify** [comment]
@JinIgarashi 
This task has a relatively high priority for me. This is because I need this feature for my work and I have received feedback from other users.

So my suggestion is that we focus mainly on implementing v1.0.0, and I'll work on this task personally. (Of course, I would welcome others to implement this.)

**Comment by JinIgarashi** [comment]
@naogify I see. If so, you can still add a function to increase port number in current version if it is already used. Also, `8080` is being used widely, conflicts can be often occurred. We may change base port number like `3000` of nginx
