### ISSUE TITLE
Release v0.1.3

### ISSUE THREAD

**Issue by JinIgarashi** [unvt/charites#75]
@naogify Could you release current main branch as v0.1.3, then we can create new branch for v1 to start implementing new CLI interface.

**Comment by naogify** [comment]
@JinIgarashi 
I got it. However, I need to add BDD tests to make sure there are no bugs, then I will release it.
I'll create PR for the BDD tests in a few days.

**Comment by JinIgarashi** [comment]
@naogify It looks like taking time for you to implement tests. Let me release the current source code as v0.1.3. You can release v0.1.4 after implementing tests.
So, users can easily use tilejson features by installing NPM

**Comment by JinIgarashi** [comment]
released v0.1.3 now

**Comment by naogify** [comment]
@JinIgarashi 
Ok, I understand. I'll release a later version that implements the test.
