### ISSUE TITLE
Implementation of i18n and transifex for documentation

### ISSUE THREAD

**Issue by JinIgarashi** [unvt/charites#83]
It requires to implement i18n together with Transifex in order to translate documentation in multiple languages after this PR (https://github.com/unvt/charites/pull/78) will be merged.

References
- Sphinx internationalization: https://www.sphinx-doc.org/en/master/usage/advanced/intl.html
- Github Actions for transifex: https://github.com/marketplace/actions/github-transifex-actions
- Example existing implementation
  - [lizmap-documentation](https://github.com/3liz/lizmap-documentation)
  - [QField-docs](https://github.com/opengisch/QField-docs)

@ubukawa @hfu ドキュメントのPR#78がマージされたのち、Transifexでcharitesのドキュメントのi18n対応を行いたいのですが、Transifex内で組織を作る必要があります。私の方でunvtという組織を作ってしまっていいでしょうか？その後、おふたりに管理者としてインビテーションを送りたいと思います。Transifexのアカウントはお持ちですか？

**Comment by hfu** [comment]
Transifex で unvt の組織を作ることについて、異論ありません。私は Transifex のアカウントを持っていません。この機会に hfujimura という名前ででもアカウントを作ることを考えています。

**Comment by JinIgarashi** [comment]
@hfu ありがとうございます。Transifexに以下の組織とプロジェクトを作ってみました。TransifexのアクセストークンをGithub repositoryに設定したいのですが、charitesリポジトリのsettingsでsecretsを編集できるようにしてもらうことは可能でしょうか？
https://www.transifex.com/unvt/charites-docs

**Comment by JinIgarashi** [comment]
@hfu @ubukawa  ひとまずドラフトPRで作ってみました。リポジトリのsecretに登録する権限をいただけたら、テストしたいと思います。

あとお二人のtransifexのユーザー名か登録するのに使ったメールアドレス教えてください。管理者として招待します。GithubアカウントでTransifexにログインできるのでそれが一番簡単だと思います。

**Comment by hfu** [comment]
@JinIgarashi を unvt/charites の Admin に追加しました。

**Comment by JinIgarashi** [comment]
@hfu ありがとうございます。`TX_TOKEN`をリポジトリのsecretsに登録させていただきました。私の個人のTransifexアカウントで作ったトークンですので、おいおい@hfuのトークンに変えるのが良いかもしれません。

**Comment by JinIgarashi** [comment]
@hfu @ubukawa PRマージしました。無事Transifex連携できました。UTC0時0分に毎日Github Actionが起動してTransifexに最新のドキュメントファイルをアップロード＆プルして、Github pagesのサイトを更新します。

以下のページの下の方に、英語版と日本語版のリンクを追記しています。HTMLフォルダのルートにはリダイレクトとかするような感じにしたほうがいい気がしていますが、ひとまず英語版にHTMLをそのまま置いています。
https://unvt.github.io/charites/

- 英語版：https://unvt.github.io/charites/en
- 日本語版：https://unvt.github.io/charites/ja

secrets追加できたので、私のアカウントからadmin権限削除していただいて構いません。
