### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by JinIgarashi** [unvt/charites#97]
This issue is for adding contributors

**Comment by JinIgarashi** [comment]
@all-contributors please add @miya0001  for code

**Comment by JinIgarashi** [comment]
@hfu @ubukawa I just requested to add all contributors in README through the following PR:

- #98
- #99 
- #100 
- #101 
- #102 
- #103 
- #104 

Could you merge these pull requests to main branch?

**Comment by ubukawa** [comment]
Thank you for your kind efforts!
I will merge them.
(I cannot do it all at once, but I will do it gradually!)

Have a good weekend.

**Comment by ubukawa** [comment]
I have merged all contributors.
I did not pay attention to the order, please feel free to modify the order if you want.

Yours, Taro

**Comment by JinIgarashi** [comment]
@ubukawa Thank you for merging them! I will close this issue now. But we can reopen this issue in case new contributers need to be added.
